# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8425d4ade146602ddc1b386c60eaf17321af0e409be5014ab87d85bf6f575b1289a4379612b72a2dcba55552d10552228a56402591c99eaf0f38657960921d5

test:
  secret_key_base: 7e75f52bea7352e0f8a449032b76c60a95e0f7d47a2c894b0bcd21d13601036d098ace1f8389e6ba97994f019523d596b63a08e1a84905c87c69f0cf9deda232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
